mysite/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('claims/submit/', views.submit, name='submit'),
    path('claims/manage/<int:claim_id>', views.manage, name='manage'),
    path('claims/manage/<int:claim_id>/delete', views.delete, name='delete'),
]

mysite/index/urls.py
from django.urls import path

from . import views

app_name = 'index'
urlpatterns = [
    path('', views.index, name='index'),
]

mysite/logout/urls.py
from django.urls import path

from . import views

app_name = 'logout'
urlpatterns = [
    path('', views.LogoutView.as_view(), name='index')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('signup/', include('signup.urls')),
    path('login/', include('login.urls')),
    path('logout/', include('logout.urls')),
    path('dashboard/', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# The concatenation above is NOT RECOMMENDED for production. Use Nginx or something else instead.

mysite/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'base/main.css' %}">
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mr.Motor's Insurance{% endblock %}</title>
</head>
<body>
    <header id="banner">
        <a href="{% url 'index:index' %}">
            <h1 id="logo">Mr. Motor's Insurance</h1>
        </a>
        {% if user.is_authenticated %}
        <div class="right-controls">
            <a href="{% url 'dashboard:submit' %}" class="btn btn-outline-primary">New claim</a>
            <a href="{% url 'dashboard:index' %}" class="btn btn-outline-success">Dashboard</a>
            <a href="{% url 'logout:index' %}" class="btn btn-outline-danger">Logout</a>
        </div>
        {% endif %}
    </header>
    {% if messages %}
        {% for message in messages %}
            <div class="c-alert alert alert-{% if message.tags == 'success' or message.tags == 'warning'  %}{{ message.tags  }}{% else %}danger{% endif %} alert-dismissable fade show" role="alert">
                {{ message }}
                <button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>